# Generated by Django 4.2a1 on 2023-02-07 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('edad', models.IntegerField()),
                ('pais', models.CharField(default='', max_length=27)),
                ('dni', models.CharField(default=0, max_length=8)),
                ('vigente', models.BooleanField(default=True)),
            ],
        ),
    ]
